config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  get "/delete_all", to: "articles#delete_all", as: "delete_all"
  get "/find_by", to: "articles#find_by", as: "find_by"
  get "/joins", to: "articles#joins", as: "joins"
  get "/rules", to: "articles#rules", as: "rules"

  get "/users/regenerate", to: "users#regenerate", as: "regenerate_users"
  get "/users/destroy_all", to: "users#destroy_all", as: "destroy_all_user"
  post "/users/destroy", to: "users#destroy", as: "destroy_user"
  post "/users/destroy_sanitized", to: "users#destroy_sanitized", as: "destroy_sanitized_user"

  post "/users/find_by", to: "users#find_by", as: "find_by_user"
  post "/users/find_by_sanitized", to: "users#find_by_sanitized", as: "find_by_user_sanitized"

  get "/orders/regenerate", to: "orders#regenerate", as: "regenerate_orders"
  get "/orders/destroy_all", to: "orders#destroy_all", as: "destroy_all_orders"

  post "/orders/joins", to: "orders#joins", as: "joins_order"
  post "/orders/joins_sanitized", to: "orders#joins_sanitized", as: "joins_sanitized_order"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'faker'
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def delete_all
    @users = User.all
    @user = @users.first
  end

  def find_by
    @users = User.all
    @user = @users.first
    @user_last = @users.last
  end

  def joins
    @orders = Order.all
  end

  def rules
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def regenerate
    Order.all.destroy_all
    10.times { User.create(name: Faker::Name.name, is_admin: User.all.count == 3) } if User.all.empty?
    10.times { Order.create(user: User.first, total: Faker::Number.within(range: 1..2000)) }

    redirect_back(fallback_location: root_path)
  end

  def destroy_all
    Order.destroy_all

    redirect_back(fallback_location: root_path)
  end

  def joins
    order_search = Order.joins(params[:table]).where("total > 1000").all

    render turbo_stream: turbo_stream.replace(:orders, partial: "orders/orders", locals: { orders: order_search })
  end

  def joins_sanitized
    order_search = Order.joins("INNER JOIN users ON users.#{ActiveRecord::Base.connection.quote_column_name(params[:column])} = orders.user_id").where("total > 1000").all
    render turbo_stream: turbo_stream.replace(:orders, partial: "orders/orders", locals: { orders: order_search })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def regenerate
    User.all.destroy_all
    10.times { User.create(name: Faker::Name.name, is_admin: User.all.count == 3) }

    redirect_back(fallback_location: root_path)
  end

  def destroy
    User.where("id = #{params[:user_id]}").delete_all

    redirect_back(fallback_location: root_path)
  end

  def destroy_sanitized
    User.where(id: params[:user_id]).delete_all

    redirect_back(fallback_location: root_path)
  end

  def destroy_all
    User.destroy_all

    redirect_back(fallback_location: root_path)
  end

  def find_by
    user_search = User.find_by(params[:id])

    render turbo_stream: turbo_stream.replace(:user, partial: "users/user", locals: { user: user_search })
  end

  def find_by_sanitized
    user_search = User.find_by(id: params[:id])

    render turbo_stream: turbo_stream.replace(:user, partial: "users/user", locals: { user: user_search })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/delete_all.html.erb
<h1 class="mb-5">delete_all</h1>

<% if @users.empty? %>
  <%= link_to "Generate users", regenerate_users_path, class: "btn btn-success" %>

  <div class="mt-5">
    <p><i>No users found</i></p>
  </div>

<% else %>
  <div class="row">
    <div class="col">
      <%= link_to "Regenerate users", regenerate_users_path, class: "btn btn-success" %>
      <%= link_to "Destroy all users", destroy_all_user_path, class: "btn btn-outline-danger" %>

      <div class="mt-5">
        <%= render partial: "users/table", locals: { users: @users } %>
      </div>
    </div>

    <div class="col">
      <h5 class="text-danger">DON'T</h5>

      <div class="do-dont-block">
        <pre><code class="language-ruby">User.where("id = #{params[:user_id]}").delete_all</code></pre>

        <pre><code class="language-sql">DELETE * FROM 'users' WHERE (id = <%= @user.id %>)</code></pre>

        <%= form_with url: :destroy_user do |f| %>
          <%= f.hidden_field :user_id, value: @user.id %>
          <%= f.submit "Delete (id = #{@user.id})", class: "btn btn-outline-primary mb-3" %>
        <% end %>

        <div class="mt-3"></div>

        <pre><code class="language-sql">DELETE * FROM 'users' WHERE (id = <%= @user.id %>) OR 1=1--)</code></pre>

        <%= form_with url: :destroy_user do |f| %>
          <%= f.hidden_field :user_id, value: "#{@user.id}) OR 1=1--" %>
          <%= f.submit "Delet (id = \"#{@user.id}) OR 1=1--\")", class: "btn btn-outline-primary mb-3" %>
        <% end %>
      </div>

      <h5 class="text-success mt-5">DO</h5>

      <div class="do-dont-block">
        <pre><code class="language-ruby">User.where(id: params[:user_id]).delete_all</code></pre>

        <pre><code class="language-sql">DELETE * FROM 'users' WHERE (id = <%= @user.id %>)</code></pre>

        <%= form_with url: :destroy_sanitized_user do |f| %>
          <%= f.hidden_field :user_id, value: @user.id %>
          <%= f.submit "Delete (id = #{@user.id})", class: "btn btn-outline-primary mb-3" %>
        <% end %>

        <div class="mt-3">

        <pre><code class="language-sql">DELETE * FROM 'users' WHERE (id = <%= @user.id %>) OR 1=1--)</code></pre>

        <%= form_with url: :destroy_sanitized_user do |f| %>
          <%= f.hidden_field :user_id, value: "#{@user.id}) OR 1=1--" %>
          <%= f.submit "Delete (id = \"#{@user.id}) OR 1=1--\")", class: "btn btn-outline-primary mb-3" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/find_by.html.erb
<h1 class="mb-5">find_by</h1>

<% if @users.empty? %>
  <%= link_to "Generate users", regenerate_users_path, class: "btn btn-success" %>

  <div class="mt-5">
    <p><i>No users found</i></p>
  </div>

<% else %>
  <div class="row">
    <div class="col">
      <%= link_to "Regenerate users", regenerate_users_path, class: "btn btn-success" %>
      <%= link_to "Destroy all users", destroy_all_user_path, class: "btn btn-outline-danger" %>

      <div class="mt-5">
        <%= render partial: "users/table", locals: { users: @users } %>
      </div>

      <div class="mt-5">
        <%= turbo_frame_tag :user %>
      </div>
    </div>

    <div class="col">
      <h5 class="text-danger">DON'T</h5>

      <div class="do-dont-block">
        <pre><code class="language-ruby">User.find_by(params[:id])</code></pre>

        <pre><code class="language-sql">SELECT * FROM 'users' WHERE (id = <%= @user.id %>)</code></pre>

        <%= form_with url: :find_by_user do |f| %>
          <%= f.hidden_field :id, value: "id = #{@user.id}" %>
          <%= f.submit "Find by (id = #{@user.id})", class: "btn btn-outline-primary mb-3" %>
        <% end %>

        <div class="mt-3"></div>

        <pre><code class="language-sql">SELECT * FROM 'users' WHERE (is_admin = true)</code></pre>

        <%= form_with url: :find_by_user do |f| %>
          <%= f.hidden_field :id, value: "is_admin = true" %>
          <%= f.submit "Find by (is_admin = true)", class: "btn btn-outline-primary mb-3" %>
        <% end %>
      </div>

      <h5 class="text-success mt-5">DO</h5>

      <div class="do-dont-block">
        <pre><code class="language-ruby">User.find_by(id: params[:id])</code></pre>

        <pre><code class="language-sql">SELECT * FROM 'users' WHERE (id = <%= @user.id %>)</code></pre>

        <%= form_with url: :find_by_user_sanitized do |f| %>
          <%= f.hidden_field :id, value: "#{@user.id}" %>
          <%= f.submit "Find by (id = #{@user.id})", class: "btn btn-outline-primary mb-3" %>
        <% end %>

        <div class="mt-3"></div>

        <pre><code class="language-sql">SELECT * FROM 'users' WHERE (id = "is_admin = true")</code></pre>

        <%= form_with url: :find_by_user_sanitized do |f| %>
          <%= f.hidden_field :id, value: "is_admin = true" %>
          <%= f.submit "Find by (id = \"is_admin = true\")", class: "btn btn-outline-primary mb-3" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/index.html.erb
<h1>What Is SQL Injection?</h1>

<p>SQL Injection is a web application attack where the attacker “injects” SQL statements that will manipulate or access application data, whether it be sensitive or public. These attacks leverage areas in web applications that ask for user input. If user inputs in an app are not sanitized properly, an attacker can use a SQL injection to gain access to the associated app datastore.<p>

<h2 class="mt-5">An Example SQL Injection</h2>

<p>Attackers commonly use SQL injections to infiltrate web applications through user input. This includes form fills for usernames, user IDs, first and last names, and more. If you do not sanitize these inputs before accepting them or make strong use of parameterized SQL statements, an attacker can pass SQL statements through that input that unknowingly run on your database.</p>

<p>For example, say you are taking the input of a user ID in from a user. When your application fetches information about a user, the URL may look something like this:</p>

<pre><code class="language-sql">SELECT * FROM users WHERE id = '42'</code></pre>


<p>They enter their user ID, you take in their input, use it to find their information in your database, and display their data for them.</p>

<p>But, consider this: instead of inputting their user ID, they input what can be interpreted as a SQL query. For example:</p>

<pre><code class="language-sql">'42' OR '1'='1'</code></pre>

<p>If you take their input as-is, without sanitizing, this will result in a SQL query like:</p>

<pre><code class="language-sql">SELECT * FROM users WHERE id = '42' OR '1'='1';</code></pre>

<p>Since 1=1 is always true, this will return every data field for all users. This is a classic example of a SQL injection.</p>

<p>It’s important to note that this is the output the database is designed to give for this type of query. In this instance, the attacker is not looking to break the application you’ve made…just use what’s already available to access things they shouldn’t. When developing an application, try to consider what things might be accessible that shouldn’t be, and then implement ways to prevent that access from happening.</p>

app/views/articles/joins.html.erb
<h1 class="mb-5">joins</h1>

<% if @orders.empty? %>
  <%= link_to "Generate orders", regenerate_orders_path, class: "btn btn-success" %>

  <div class="mt-5">
    <p><i>No orders found</i></p>
  </div>

<% else %>
  <div class="row">
    <div class="col">
      <%= link_to "Regenerate orders", regenerate_orders_path, class: "btn btn-success" %>
      <%= link_to "Destroy all orders", destroy_all_orders_path, class: "btn btn-outline-danger" %>

      <div class="mt-5">
        <%= render partial: "orders/table", locals: { orders: @orders } %>
      </div>

      <div class="mt-5">
        <%= turbo_frame_tag :orders %>
      </div>
    </div>

    <div class="col">
      <h5 class="text-danger">DON'T</h5>

      <div class="do-dont-block">
        <pre><code class="language-ruby">Order.joins(params[:table]).where("total > 1000").all</code></pre>

        <pre><code class="language-sql">SELECT "orders".* FROM "orders" INNER JOIN users ON users.id = orders.user_id WHERE (total > 1000)</code></pre>

        <%= form_with url: :joins_order do |f| %>
          <%= f.hidden_field :table, value: "INNER JOIN users ON users.id = orders.user_id" %>
          <%= f.submit "Joins (INNER JOIN users ON users.id = orders.user_id)", class: "btn btn-outline-primary mb-3" %>
        <% end %>

        <pre><code class="language-sql">SELECT "orders".* FROM "orders" -- WHERE (total > 1000)</code></pre>

        <%= form_with url: :joins_order do |f| %>
          <%= f.hidden_field :table, value: "--" %>
          <%= f.submit "Joins (--)", class: "btn btn-outline-primary mb-3" %>
        <% end %>

        <div class="mt-3"></div>
      </div>

      <h5 class="text-success">DO</h5>

      <div class="do-dont-block">
        <pre><code class="language-ruby">Order.joins("INNER JOIN users ON users
        .#{ActiveRecord::Base.connection.quote_column_name(params[:column])} = orders.user_id")
        .where("total > 1000").all</code></pre>

        <%= form_with url: :joins_sanitized_order do |f| %>
          <%= f.hidden_field :column, value: "id" %>
          <%= f.submit "Joins (id)", class: "btn btn-outline-primary mb-3" %>
        <% end %>

        <pre><code class="language-sql">SELECT "orders".* FROM "orders" INNER JOIN users ON users."--" = orders.user_id WHERE (total > 1000)</code></pre>

        <%= form_with url: :joins_sanitized_order do |f| %>
          <%= f.hidden_field :column, value: "--" %>
          <%= f.submit "Joins (--)", class: "btn btn-outline-primary mb-3" %>
        <% end %>

        <div class="mt-3"></div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/rules.html.erb
<h1>General Rules</h1>

<h3 class="mt-4">String Conditions</h3>

<h5 class="text-danger">DON'T</h5>

<div class="do-dont-block">
  <pre><code class="language-ruby">Post.where("category = #{params[:category]}")</code></pre>
</div>

<h5 class="text-success">DO</h5>

<div class="do-dont-block">
  <pre><code class="language-ruby">Post.where(category: params[:category])</code></pre>
</div>

<h3 class="mt-4">Array Conditions</h3>

<h5 class="text-success">DO</h5>

<div class="do-dont-block">
  <pre><code class="language-ruby">Post.where("category = ?", params[:category])</code></pre>

  <pre><code class="language-ruby">Post.where("category = ? AND published = ?", params[:category], true)</code></pre>
</div>

<h3 class="mt-4">Hash Conditions</h3>

<h5 class="text-success">DO</h5>

<div class="do-dont-block">
  <pre><code class="language-ruby">Post.where(category: params[:category])</code></pre>
</div>

<h3 class="mt-4">Best Practices</h3>

<h5 class="text-success">DO</h5>

<ol>
  <li>Use <b>hash conditions</b> whenever possible.</li>
  <li>Avoid using string conditions.</li>
  <li>Definitely avoid using string interpolation inside these conditions.</li>
  <li>If you need to pass a variable or any user input to a query, use <b>array conditions</b>.</li>
</ol>

<h3 class="mt-4">Other Recommendations</h3>

<h5 class="text-success">DO</h5>

<p>Use <%= link_to "Brakeman", "https://brakemanscanner.org/" %>.</p>
<p>It is specifically aimed at analyzing potential security issues in your Ruby on Rails code.</p>

app/views/layouts/_sidebar.html.erb
<nav class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
    <span class="fs-4">Rails SQL Injections</span>
  </a>

  <hr>

  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item"><%= link_to "What is SQL Injections", root_path, class: "nav-link link-dark" %></li>
    <li><%= link_to "delete_all", delete_all_path, class: "nav-link link-dark" %></li>
    <li><%= link_to "find_by", find_by_path, class: "nav-link link-dark" %></li>
    <li><%= link_to "joins", joins_path, class: "nav-link link-dark" %></li>
    <li><%= link_to "General Rules", rules_path, class: "nav-link link-dark" %></li>
</nav>

<div class="b-example-divider b-example-vr"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails SQL Injections</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="d-flex flex-nowrap">
      <%= render partial: "layouts/sidebar" %>

      <main class="p-3 w-100">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/orders/_orders.html.erb
<%= turbo_frame_tag :orders do %>
  <h1>Founded orders</h1>

  <% if orders %>
    <% orders.each do |order| %>
      <p>
        <code><%= order.id %></code>
        <%= order.total %>
      </p>
    <% end %>

  <% else %>
    <p><code>nil</p>

  <% end %>
<% end %>

app/views/orders/_table.html.erb
<table class="table table-borderless">
  <tr>
    <th>ID</th>
    <th>Total</th>
  </tr>

  <% orders.each do |order| %>
    <tr id="<%= dom_id order %>">
      <td><code><%= order.id %></code></td>
      <td><%= order.total %></td>
    </tr>
  <% end %>
</table>

app/views/users/_table.html.erb
<table class="table table-borderless">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Admin?</th>
  </tr>

  <% users.each do |user| %>
    <tr id="<%= dom_id user %>">
      <td><code><%= user.id %></code></td>
      <td><%= user.name %></td>
      <td><code><%= user.is_admin ? "Yes" : "" %></code></td>
    </tr>
  <% end %>
</table>

app/views/users/_user.html.erb
<%= turbo_frame_tag :user do %>
  <h1>Founded user</h1>

  <% if user %>
    <p>
      <code><%= user.id %></code>
      <%= user.name %>
      <code><%= user.is_admin ? "Admin" : "" %></code>
    </p>
  <% else %>
    <p><code>nil</p>
  <% end %>
<% end %>